before:
  hooks:
    - go mod download

builds:
  - id: protoc-gen-go-iam
    binary: protoc-gen-go-iam
    dir: ./cmd/protoc-gen-go-iam
    main: main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next"

release:
  github:
  prerelease: auto
