package generator

import "google.golang.org/protobuf/compiler/protogen"

type FileHeader struct {
	File *protogen.File
}

func (g FileHeader) Generate(f *protogen.GeneratedFile) {
	f.P("// Code generated by iam-go. DO NOT EDIT.")
	f.P("//")
	f.P("// source: ", g.File.Desc.Path())
	f.P()
	f.P("package ", g.File.GoPackageName)
}
